todo/urls.py
from django.urls import path

from todo.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView, completion,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/create", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete", TagDeleteView.as_view(), name="tag-delete"),
    path("tasks/<int:pk>/complete", completion, name="task-complete"),

]

app_name = "todo"

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=60)


class Task(models.Model):
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["complete", "created"]

    def __str__(self):
        return f"{self.content} {self.deadline}"






todo/views.py

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "todo/task_list.html"
    paginate_by = 2


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "todo/task_confirm_delete.html"
    success_url = reverse_lazy("todo:task-list")


def completion(request):
    if Task.complete:
        Task.complete = False
    else:
        Task.complete = True
    return render(request, "todo/task_list.html")


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "todo/tag_list.html"
    paginate_by = 2


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "todo/tag_confirm_delete.html"
    success_url = reverse_lazy("todo:tag-list")


todo/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>ToDo list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

todo/templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

todo/templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:index' %}">Home</a></li>
    <br>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

todo/templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Task</h1>

    <p>Are you sure you want to delete the tag: {{ tag }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
    </form>
{% endblock %}

todo/templates/todo/tag_form.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object|yesno:"Update,Create" }} Tag</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Submit">
    </form>
{% endblock %}

todo/templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
        Tag List
        <a style="float: right" href="{% url 'todo:tag-create' %}">Add</a>
    </h1>

    {% if tag_list %}
      <table class="table">
        <tr>
          <th>Name</th>
            <th>Update</th>
          <th>Delete</th>
        </tr>

        {% for tag in tag_list %}
            <tr>
              <td>
                  {{ tag.name}}
              </td>
                <td>
                  <a href="{% url "todo:tag-update" pk=tag.id %}">UPDATE</a>
              </td>
              <td>
                  <a href="{% url "todo:tag-delete" pk=tag.id %}">DELETE</a>
              </td>
          </tr>
        {% endfor %}
      </table>

    {% else %}
        <p>There are no tags in the TODO list.</p>
    {% endif %}
{% endblock %}

todo/templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Task</h1>

    <p>Are you sure you want to delete the task: {{ task }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
    </form>
{% endblock %}

todo/templates/todo/task_form.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object|yesno:"Update,Create" }} Task</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Submit">
    </form>
{% endblock %}

todo/templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
      TODO list
      <a style="float: right" href="{% url 'todo:task-create' %}">Add task</a>
  </h1>
  {% if task_list %}
    <ul>
      {% for task in task_list %}
        <li>
            {{ task.content }}
            {% if task.complete %}
                Done
             <a style="float: right" href="{% url 'todo:task-complete' pk=task.id %}">Undo</a>
            {% else %}
                Not done
                <a style="float: right" href="{% url 'todo:task-complete' pk=task.id %}">Complete</a>
            {% endif %}
        Created: {{ task.created }}
        Deadline: {{ task.deadline }}
        Tags:
        {% for tag in task.tags.all %}
            {{ tag.name }}
        {% endfor %}
        <a href="{% url 'todo:task-update' pk=task.id %}">UPDATE</a>
        <a href="{% url 'todo:task-delete' pk=task.id %}">DELETE</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no tasks in TODO list</p>
  {% endif %}
{% endblock %}